# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/Users/durgatej/development/terraform/test/tej-iam/env/rnd/test-user-with-keys-and-secrets/terraform.tfstate"
  }
}
